services:
  - type: web
    name: fastapi-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
    env:
      - key: PORT
        value: 10000
